# Visit 3.4.2 log file
ScriptVersion = "3.4.2"
if ScriptVersion != Version():
    print "This script is for VisIt %s. It may not work with version %s" % (ScriptVersion, Version())
ShowAllWindows()
OpenDatabase("/home/exy214/Documents/cavitation/data/jetting_ws_2025/runs/PostProc/domain/domain_0.*.xdmf database", 0)
# The UpdateDBPluginInfo RPC is not supported in the VisIt module so it will not be logged.
AddPlot("Pseudocolor", "diffuse volume fraction 1", 1, 1)
AddOperator("Reflect", 1)
AddOperator("Slice", 1)
AddOperator("Isosurface", 1)
SetActivePlots(0)
ReflectAtts = ReflectAttributes()
ReflectAtts.octant = ReflectAtts.PXPYPZ  # PXPYPZ, NXPYPZ, PXNYPZ, NXNYPZ, PXPYNZ, NXPYNZ, PXNYNZ, NXNYNZ
ReflectAtts.useXBoundary = 1
ReflectAtts.specifiedX = 0
ReflectAtts.useYBoundary = 1
ReflectAtts.specifiedY = 0
ReflectAtts.useZBoundary = 1
ReflectAtts.specifiedZ = 0
ReflectAtts.reflections = (1, 0, 1, 0, 0, 0, 0, 0)
ReflectAtts.planePoint = (0, 0, 0)
ReflectAtts.planeNormal = (0, 0, 0)
ReflectAtts.reflectType = ReflectAtts.Axis  # Plane, Axis
SetOperatorOptions(ReflectAtts, 0, 1)
SetActivePlots(0)
SetActivePlots(0)
SliceAtts = SliceAttributes()
SliceAtts.originType = SliceAtts.Intercept  # Point, Intercept, Percent, Zone, Node
SliceAtts.originPoint = (0, 0, 0)
SliceAtts.originIntercept = 0
SliceAtts.originPercent = 0
SliceAtts.originZone = 0
SliceAtts.originNode = 0
SliceAtts.normal = (0, -1, 0)
SliceAtts.axisType = SliceAtts.YAxis  # XAxis, YAxis, ZAxis, Arbitrary, ThetaPhi
SliceAtts.upAxis = (0, 0, 1)
SliceAtts.project2d = 1
SliceAtts.interactive = 1
SliceAtts.flip = 0
SliceAtts.originZoneDomain = 0
SliceAtts.originNodeDomain = 0
SliceAtts.meshName = "default"
SliceAtts.theta = 0
SliceAtts.phi = 0
SetOperatorOptions(SliceAtts, 1, 1)
SetActivePlots(0)
SetActivePlots(0)
IsosurfaceAtts = IsosurfaceAttributes()
IsosurfaceAtts.contourNLevels = 10
IsosurfaceAtts.contourValue = ()
IsosurfaceAtts.contourPercent = ()
IsosurfaceAtts.contourMethod = IsosurfaceAtts.Level  # Level, Value, Percent
IsosurfaceAtts.minFlag = 0
IsosurfaceAtts.min = 0
IsosurfaceAtts.maxFlag = 0
IsosurfaceAtts.max = 1
IsosurfaceAtts.scaling = IsosurfaceAtts.Linear  # Linear, Log
IsosurfaceAtts.variable = "default"
SetOperatorOptions(IsosurfaceAtts, 1, 1)
SetActivePlots(0)
DrawPlots()
SetTimeSliderState(0)
Query("Time")
Query("Total Length")
SetTimeSliderState(1)
Query("Time")
Query("Total Length")
SetTimeSliderState(2)
Query("Time")
Query("Total Length")
SetTimeSliderState(3)
Query("Time")
Query("Total Length")
SetTimeSliderState(4)
Query("Time")
Query("Total Length")
SetTimeSliderState(5)
Query("Time")
Query("Total Length")
SetTimeSliderState(6)
Query("Time")
Query("Total Length")
SetTimeSliderState(7)
Query("Time")
Query("Total Length")
SetTimeSliderState(8)
Query("Time")
Query("Total Length")
SetTimeSliderState(9)
Query("Time")
Query("Total Length")
SetTimeSliderState(10)
Query("Time")
Query("Total Length")
SetTimeSliderState(11)
Query("Time")
Query("Total Length")
SetTimeSliderState(12)
Query("Time")
Query("Total Length")
SetTimeSliderState(13)
Query("Time")
Query("Total Length")
SetTimeSliderState(14)
Query("Time")
Query("Total Length")
SetTimeSliderState(15)
Query("Time")
Query("Total Length")
SetTimeSliderState(16)
Query("Time")
Query("Total Length")
SetTimeSliderState(17)
Query("Time")
Query("Total Length")
SetTimeSliderState(18)
Query("Time")
Query("Total Length")
SetTimeSliderState(19)
Query("Time")
Query("Total Length")
SetTimeSliderState(20)
Query("Time")
Query("Total Length")
SetTimeSliderState(21)
Query("Time")
Query("Total Length")
SetTimeSliderState(22)
Query("Time")
Query("Total Length")
SetTimeSliderState(23)
Query("Time")
Query("Total Length")
SetTimeSliderState(24)
Query("Time")
Query("Total Length")
SetTimeSliderState(25)
Query("Time")
Query("Total Length")
SetTimeSliderState(26)
Query("Time")
Query("Total Length")
SetTimeSliderState(27)
Query("Time")
Query("Total Length")
SetTimeSliderState(28)
Query("Time")
Query("Total Length")
SetTimeSliderState(29)
Query("Time")
Query("Total Length")
SetTimeSliderState(30)
Query("Time")
Query("Total Length")
SetTimeSliderState(31)
Query("Time")
Query("Total Length")
SetTimeSliderState(32)
Query("Time")
Query("Total Length")
SetTimeSliderState(33)
Query("Time")
Query("Total Length")
SetTimeSliderState(34)
Query("Time")
Query("Total Length")
SetTimeSliderState(35)
Query("Time")
Query("Total Length")
SetTimeSliderState(36)
Query("Time")
Query("Total Length")
SetTimeSliderState(37)
Query("Time")
Query("Total Length")
SetTimeSliderState(38)
Query("Time")
Query("Total Length")
SetTimeSliderState(39)
Query("Time")
Query("Total Length")
SetTimeSliderState(40)
Query("Time")
Query("Total Length")
SetTimeSliderState(41)
Query("Time")
Query("Total Length")
SetTimeSliderState(42)
Query("Time")
Query("Total Length")
SetTimeSliderState(43)
Query("Time")
Query("Total Length")
SetTimeSliderState(44)
Query("Time")
Query("Total Length")
SetTimeSliderState(45)
Query("Time")
Query("Total Length")
SetTimeSliderState(46)
Query("Time")
Query("Total Length")
SetTimeSliderState(47)
Query("Time")
Query("Total Length")
SetTimeSliderState(48)
Query("Time")
Query("Total Length")
SetTimeSliderState(49)
Query("Time")
Query("Total Length")
SetTimeSliderState(50)
Query("Time")
Query("Total Length")
SetTimeSliderState(51)
Query("Time")
Query("Total Length")
SetTimeSliderState(52)
Query("Time")
Query("Total Length")
SetTimeSliderState(53)
Query("Time")
Query("Total Length")
SetTimeSliderState(54)
Query("Time")
Query("Total Length")
SetTimeSliderState(55)
Query("Time")
Query("Total Length")
SetTimeSliderState(56)
Query("Time")
Query("Total Length")
SetTimeSliderState(57)
Query("Time")
Query("Total Length")
SetTimeSliderState(58)
Query("Time")
Query("Total Length")
SetTimeSliderState(59)
Query("Time")
Query("Total Length")
SetTimeSliderState(60)
Query("Time")
Query("Total Length")
SetTimeSliderState(61)
Query("Time")
Query("Total Length")
SetTimeSliderState(62)
Query("Time")
Query("Total Length")
SetTimeSliderState(63)
Query("Time")
Query("Total Length")
SetTimeSliderState(64)
Query("Time")
Query("Total Length")
SetTimeSliderState(65)
Query("Time")
Query("Total Length")
SetTimeSliderState(66)
Query("Time")
Query("Total Length")
SetTimeSliderState(67)
Query("Time")
Query("Total Length")
SetTimeSliderState(68)
Query("Time")
Query("Total Length")
SetTimeSliderState(69)
Query("Time")
Query("Total Length")
SetTimeSliderState(70)
Query("Time")
Query("Total Length")
SetTimeSliderState(71)
Query("Time")
Query("Total Length")
SetTimeSliderState(72)
Query("Time")
Query("Total Length")
SetTimeSliderState(73)
Query("Time")
Query("Total Length")
SetTimeSliderState(74)
Query("Time")
Query("Total Length")
SetTimeSliderState(75)
Query("Time")
Query("Total Length")
SetTimeSliderState(76)
Query("Time")
Query("Total Length")
SetTimeSliderState(77)
Query("Time")
Query("Total Length")
SetTimeSliderState(78)
Query("Time")
Query("Total Length")
SetTimeSliderState(79)
Query("Time")
Query("Total Length")
SetTimeSliderState(80)
Query("Time")
Query("Total Length")
SetTimeSliderState(81)
Query("Time")
Query("Total Length")
SetTimeSliderState(82)
Query("Time")
Query("Total Length")
SetTimeSliderState(83)
Query("Time")
Query("Total Length")
SetTimeSliderState(84)
Query("Time")
Query("Total Length")
SetTimeSliderState(85)
Query("Time")
Query("Total Length")
SetTimeSliderState(86)
Query("Time")
Query("Total Length")
SetTimeSliderState(87)
Query("Time")
Query("Total Length")
SetTimeSliderState(88)
Query("Time")
Query("Total Length")
SetTimeSliderState(89)
Query("Time")
Query("Total Length")
SetTimeSliderState(90)
Query("Time")
Query("Total Length")
SetTimeSliderState(91)
Query("Time")
Query("Total Length")
SetTimeSliderState(92)
Query("Time")
Query("Total Length")
SetTimeSliderState(93)
Query("Time")
Query("Total Length")
SetTimeSliderState(94)
Query("Time")
Query("Total Length")
SetTimeSliderState(95)
Query("Time")
Query("Total Length")
SetTimeSliderState(96)
Query("Time")
Query("Total Length")
SetTimeSliderState(97)
Query("Time")
Query("Total Length")
SetTimeSliderState(98)
Query("Time")
Query("Total Length")
SetTimeSliderState(99)
Query("Time")
Query("Total Length")
SetTimeSliderState(100)
Query("Time")
Query("Total Length")
SetTimeSliderState(101)
Query("Time")
Query("Total Length")
SetTimeSliderState(102)
Query("Time")
Query("Total Length")
SetTimeSliderState(103)
Query("Time")
Query("Total Length")
SetTimeSliderState(104)
Query("Time")
Query("Total Length")
SetTimeSliderState(105)
Query("Time")
Query("Total Length")
SetTimeSliderState(106)
Query("Time")
Query("Total Length")
SetTimeSliderState(107)
Query("Time")
Query("Total Length")
SetTimeSliderState(108)
Query("Time")
Query("Total Length")
SetTimeSliderState(109)
Query("Time")
Query("Total Length")
SetTimeSliderState(110)
Query("Time")
Query("Total Length")
SetTimeSliderState(111)
Query("Time")
Query("Total Length")
SetTimeSliderState(112)
Query("Time")
Query("Total Length")
SetTimeSliderState(113)
Query("Time")
Query("Total Length")
SetTimeSliderState(114)
Query("Time")
Query("Total Length")
SetTimeSliderState(115)
Query("Time")
Query("Total Length")
SetTimeSliderState(116)
Query("Time")
Query("Total Length")
SetTimeSliderState(117)
Query("Time")
Query("Total Length")
SetTimeSliderState(118)
Query("Time")
Query("Total Length")
SetTimeSliderState(119)
Query("Time")
Query("Total Length")
SetTimeSliderState(120)
Query("Time")
Query("Total Length")
SetTimeSliderState(121)
Query("Time")
Query("Total Length")
SetTimeSliderState(122)
Query("Time")
Query("Total Length")
SetTimeSliderState(123)
Query("Time")
Query("Total Length")
SetTimeSliderState(124)
Query("Time")
Query("Total Length")
SetTimeSliderState(125)
Query("Time")
Query("Total Length")
SetTimeSliderState(126)
Query("Time")
Query("Total Length")
SetTimeSliderState(127)
Query("Time")
Query("Total Length")
SetTimeSliderState(128)
Query("Time")
Query("Total Length")
SetTimeSliderState(129)
Query("Time")
Query("Total Length")
SetTimeSliderState(130)
Query("Time")
Query("Total Length")
SetTimeSliderState(131)
Query("Time")
Query("Total Length")
SetTimeSliderState(132)
Query("Time")
Query("Total Length")
SetTimeSliderState(133)
Query("Time")
Query("Total Length")
SetTimeSliderState(134)
Query("Time")
Query("Total Length")
SetTimeSliderState(135)
Query("Time")
Query("Total Length")
SetTimeSliderState(136)
Query("Time")
Query("Total Length")
SetTimeSliderState(137)
Query("Time")
Query("Total Length")
SetTimeSliderState(138)
Query("Time")
Query("Total Length")
SetTimeSliderState(139)
Query("Time")
Query("Total Length")
SetTimeSliderState(140)
Query("Time")
Query("Total Length")
SetTimeSliderState(141)
Query("Time")
Query("Total Length")
SetTimeSliderState(142)
Query("Time")
Query("Total Length")
SetTimeSliderState(143)
Query("Time")
Query("Total Length")
SetTimeSliderState(144)
Query("Time")
Query("Total Length")
SetTimeSliderState(145)
Query("Time")
Query("Total Length")
SetTimeSliderState(146)
Query("Time")
Query("Total Length")
SetTimeSliderState(147)
Query("Time")
Query("Total Length")
SetTimeSliderState(148)
Query("Time")
Query("Total Length")
SetTimeSliderState(149)
Query("Time")
Query("Total Length")
SetTimeSliderState(150)
Query("Time")
Query("Total Length")
SetTimeSliderState(151)
Query("Time")
Query("Total Length")
SetTimeSliderState(152)
Query("Time")
Query("Total Length")
SetTimeSliderState(153)
Query("Time")
Query("Total Length")
SetTimeSliderState(154)
Query("Time")
Query("Total Length")
SetTimeSliderState(155)
Query("Time")
Query("Total Length")
SetTimeSliderState(156)
Query("Time")
Query("Total Length")
SetTimeSliderState(157)
Query("Time")
Query("Total Length")
SetTimeSliderState(158)
Query("Time")
Query("Total Length")
SetTimeSliderState(159)
Query("Time")
Query("Total Length")
SetTimeSliderState(160)
Query("Time")
Query("Total Length")
SetTimeSliderState(161)
Query("Time")
Query("Total Length")
SetTimeSliderState(162)
Query("Time")
Query("Total Length")
SetTimeSliderState(163)
Query("Time")
Query("Total Length")
SetTimeSliderState(164)
Query("Time")
Query("Total Length")
SetTimeSliderState(165)
Query("Time")
Query("Total Length")
SetTimeSliderState(166)
Query("Time")
Query("Total Length")
SetTimeSliderState(167)
Query("Time")
Query("Total Length")
SetTimeSliderState(168)
Query("Time")
Query("Total Length")
SetTimeSliderState(169)
Query("Time")
Query("Total Length")
SetTimeSliderState(170)
Query("Time")
Query("Total Length")
SetTimeSliderState(171)
Query("Time")
Query("Total Length")
SetTimeSliderState(172)
Query("Time")
Query("Total Length")
SetTimeSliderState(173)
Query("Time")
Query("Total Length")
SetTimeSliderState(174)
Query("Time")
Query("Total Length")
SetTimeSliderState(175)
Query("Time")
Query("Total Length")
SetTimeSliderState(176)
Query("Time")
Query("Total Length")
SetTimeSliderState(177)
Query("Time")
Query("Total Length")
SetTimeSliderState(178)
Query("Time")
Query("Total Length")
SetTimeSliderState(179)
Query("Time")
Query("Total Length")
SetTimeSliderState(180)
Query("Time")
Query("Total Length")
SetTimeSliderState(181)
Query("Time")
Query("Total Length")
SetTimeSliderState(182)
Query("Time")
Query("Total Length")
SetTimeSliderState(183)
Query("Time")
Query("Total Length")
SetTimeSliderState(184)
Query("Time")
Query("Total Length")
SetTimeSliderState(185)
Query("Time")
Query("Total Length")
SetTimeSliderState(186)
Query("Time")
Query("Total Length")
SetTimeSliderState(187)
Query("Time")
Query("Total Length")
SetTimeSliderState(188)
Query("Time")
Query("Total Length")
SetTimeSliderState(189)
Query("Time")
Query("Total Length")
SetTimeSliderState(190)
Query("Time")
Query("Total Length")
SetTimeSliderState(191)
Query("Time")
Query("Total Length")
SetTimeSliderState(192)
Query("Time")
Query("Total Length")
SetTimeSliderState(193)
Query("Time")
Query("Total Length")
SetTimeSliderState(194)
Query("Time")
Query("Total Length")
SetTimeSliderState(195)
Query("Time")
Query("Total Length")
SetTimeSliderState(196)
Query("Time")
Query("Total Length")
SetTimeSliderState(197)
Query("Time")
Query("Total Length")
SetTimeSliderState(198)
Query("Time")
Query("Total Length")
SetTimeSliderState(199)
Query("Time")
Query("Total Length")
SetTimeSliderState(200)
Query("Time")
Query("Total Length")
SetTimeSliderState(201)
Query("Time")
Query("Total Length")
SetTimeSliderState(202)
Query("Time")
Query("Total Length")
SetTimeSliderState(203)
Query("Time")
Query("Total Length")
SetTimeSliderState(204)
Query("Time")
Query("Total Length")
SetTimeSliderState(205)
Query("Time")
Query("Total Length")
SetTimeSliderState(206)
Query("Time")
Query("Total Length")
SetTimeSliderState(207)
Query("Time")
Query("Total Length")
SetTimeSliderState(208)
Query("Time")
Query("Total Length")
SetTimeSliderState(209)
Query("Time")
Query("Total Length")
SetTimeSliderState(210)
Query("Time")
Query("Total Length")
SetTimeSliderState(211)
Query("Time")
Query("Total Length")
SetTimeSliderState(212)
Query("Time")
Query("Total Length")
SetTimeSliderState(213)
Query("Time")
Query("Total Length")
SetTimeSliderState(214)
Query("Time")
Query("Total Length")
SetTimeSliderState(215)
Query("Time")
Query("Total Length")
SetTimeSliderState(216)
Query("Time")
Query("Total Length")
SetTimeSliderState(217)
Query("Time")
Query("Total Length")
SetTimeSliderState(218)
Query("Time")
Query("Total Length")
SetTimeSliderState(219)
Query("Time")
Query("Total Length")
SetTimeSliderState(220)
Query("Time")
Query("Total Length")
SetTimeSliderState(221)
Query("Time")
Query("Total Length")
SetTimeSliderState(222)
Query("Time")
Query("Total Length")
SetTimeSliderState(223)
Query("Time")
Query("Total Length")
SetTimeSliderState(224)
Query("Time")
Query("Total Length")
SetTimeSliderState(225)
Query("Time")
Query("Total Length")
SetTimeSliderState(226)
Query("Time")
Query("Total Length")
SetTimeSliderState(227)
Query("Time")
Query("Total Length")
SetTimeSliderState(228)
Query("Time")
Query("Total Length")
SetTimeSliderState(229)
Query("Time")
Query("Total Length")
SetTimeSliderState(230)
Query("Time")
Query("Total Length")
SetTimeSliderState(231)
Query("Time")
Query("Total Length")
SetTimeSliderState(232)
Query("Time")
Query("Total Length")
SetTimeSliderState(233)
Query("Time")
Query("Total Length")
SetTimeSliderState(234)
Query("Time")
Query("Total Length")
